### ISSUE TITLE
'scipy' is missing

### ISSUE THREAD

**Issue by tanchihpin0517** [YatingMusic/MuseMorphose#6]
'scipy' is required while computing attributes classes

```
Traceback (most recent call last):
  File "/home/tanch/workspace/MuseMorphose/attributes.py", line 1, in <module>
    from utils import pickle_load
  File "/home/tanch/workspace/MuseMorphose/utils.py", line 3, in <module>
    from scipy.spatial import distance
ModuleNotFoundError: No module named 'scipy'
```

**Comment by tanchihpin0517** [comment]
Sorry it's my carelessness. Just close it.
